from . import person
from . import contact_person
from . import diagnosis
from . import disease_type
from . import disease
from . import doctor
from . import doctor_schedule
from . import patient
from . import patient_card
from . import personal_doctor_history
from . import research_type
from . import research
from . import sample_type
from . import visit
